spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/toduck?allowPublicKeyRetrieval=true&useSSL=false
    username: user
    password: abcd1234@

  data.redis:
    host: localhost
    port: 6380
    password: abcd1234@

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false
