spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/toduck?allowPublicKeyRetrieval=true&useSSL=false
    username: user
    password: abcd1234@
  data.redis:
    host: localhost
    port: 6380
    password: abcd1234@
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false


jwt:
  secret-key:
    access-token: toduckAccessAccessAccessTokenSecretKeyForToduck
    refresh-token: toduckRefreshRefreshRefreshTokenSecretKeyForToduck
  expiration-time:
    access-token: 1_800_000 # 30m (30 * 60 * 1000)
    refresh-token: 604_800_000 # 7d (7 * 24 * 60 * 60 * 1000)
