name: Continuous Integration

on:
  pull_request:
    branches: [ "main", "develop" ]

permissions:
  contents: read
  checks: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  CI:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout PR
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          submodules: 'recursive'

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Test, Lint, Build
        run: |
          chmod +x ./gradlew
          ./gradlew build

      - name: Test Coverage Report
        id: jacoco
        uses: madrapps/jacoco-report@v1.6.1
        with:
          title: 📝 Jacoco Test Coverage
          paths: ${{ github.workspace }}/**/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 30
          min-coverage-changed-files: 50
          update-comment: true

      - name: Write Test Report
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          comment_title: 🧪 Test Results
          files: "**/build/test-results/test/TEST-*.xml"

      - name: Comment(Annotation) for Failed Test
        uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          report_paths: "**/build/test-results/test/TEST-*.xml"
